- name: Run database container
  community.docker.docker_container:
    name: my-database
    image: "{{ dockerhub_username }}/tp-devops-database:latest"
    state: started
    restart_policy: unless-stopped
    networks:
      - name: backend-db
    volumes:
      - db-data:/var/lib/postgresql/data
    env:
      POSTGRES_DB: "{{ postgres_db }}"
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
    pull: true
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python3
