- name: Run backend container
  community.docker.docker_container:
    name: my-backend
    image: "{{ dockerhub_username }}/tp-devops-simple-api:latest"
    state: started
    restart_policy: unless-stopped
    networks:
      - name: backend-db
      - name: frontend-backend
    env:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://my-database:5432/{{ postgres_db }}"
      SPRING_DATASOURCE_USERNAME: "{{ postgres_user }}"
      SPRING_DATASOURCE_PASSWORD: "{{ postgres_password }}"
    pull: true
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python3
